### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by smesdaghi** [ROGUE-JCTD/django-gsschema#8]
- layers list's default choice should be something like 'Select a layer'
- when a layer is not selected, action buttons should be disabled
- upload should only be enabled when a layer has been selected and a file specified
- in cases there is an error in upload/download/describe/remove, user needs to be notified
- download button should only be enabled when there is a file to download. 
- add tooltips to each button explaining what it really does. They should make clear what the difference between download and describe feature type is. handle tooltips same way we do for maploom

**Comment by BirdSamuel** [comment]
Fixed everything except: 
- in cases there is an error in upload/download/describe/remove, user needs to be notified

That will be worked on next.

**Comment by BirdSamuel** [comment]
Done!
